const QUOTES = [
    "If you want to achieve greatness stop asking for permission. ~Anonymous",
    "Things work out best for those who make the best of how things work out. ~John Wooden",
    "To live a creative life, we must lose our fear of being wrong. ~Anonymous",
    "If you are not willing to risk the usual you will have to settle for the ordinary. ~Jim Rohn",
    "Trust because you are willing to accept the risk, not because it's safe or certain. ~Anonymous",
    "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda",
    "All our dreams can come true if we have the courage to pursue them. ~Walt Disney",
    "Good things come to people who wait, but better things come to those who go out and get them. ~Anonymous",
    "If you do what you always did, you will get what you always got. ~Anonymous",
    "Success is walking from failure to failure with no loss of enthusiasm. ~Winston Churchill",
    "Just when the caterpillar thought the world was ending, he turned into a butterfly. ~Proverb",
    "Successful entrepreneurs are givers and not takers of positive energy. ~Anonymous",
    "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. ~Vaibhav Shah",
    "Opportunities don't happen, you create them. ~Chris Grosser",
    "Try not to become a person of success, but rather try to become a person of value. ~Albert Einstein",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people. ~Eleanor Roosevelt",
    "I have not failed. I've just found 10,000 ways that won't work. ~Thomas A. Edison",
    "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it. ~Kim Garst",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him. ~David Brinkley",
    "No one can make you feel inferior without your consent. ~Eleanor Roosevelt",
    "The whole secret of a successful life is to find out what is one's destiny to do, and then do it. ~Henry Ford",
    "If you're going through hell keep going. ~Winston Churchill",
    "The ones who are crazy enough to think they can change the world, are the ones that do. ~Anonymous",
    "Don't raise your voice, improve your argument. ~Anonymous",
    "What seems to us as bitter trials are often blessings in disguise.~ Oscar Wilde",
    "The meaning of life is to find your gift. The purpose of life is to give it away. ~Anonymous",
    "The distance between insanity and genius is measured only by success. ~Bruce Feirstein",
    "When you stop chasing the wrong things you give the right things a chance to catch you. ~Lolly Daskal",
    "Don't be afraid to give up the good to go for the great. ~John D. Rockefeller",
    "No masterpiece was ever created by a lazy artist.~ Anonymous",
    "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. ~Nathaniel Hawthorne",
    "If you can't explain it simply, you don't understand it well enough. ~Albert Einstein",
    "Blessed are those who can give without remembering and take without forgetting. ~Anonymous",
    "Do one thing every day that scares you. ~Anonymous",
    "What's the point of being alive if you don't at least try to do something remarkable. ~Anonymous",
    "Life is not about finding yourself. Life is about creating yourself. ~Lolly Daskal",
    "Nothing in the world is more common than unsuccessful people with talent. ~Anonymous",
    "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. ~Anonymous",
    "Your problem isn't the problem. Your reaction is the problem. ~Anonymous",
    "You can do anything, but not everything. ~Anonymous",
    "Innovation distinguishes between a leader and a follower. ~Steve Jobs",
    "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. ~Ray Goforth",
    "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. ~Dr. APJ Kalam",
    "I find that the harder I work, the more luck I seem to have. ~Thomas Jefferson",
    "The starting point of all achievement is desire. ~Napolean Hill",
    "Success is the sum of small efforts, repeated day-in and day-out. ~Robert Collier",
    "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. ~Thomas J. Watson",
    "All progress takes place outside the comfort zone. ~Michael John Bobak",
    "You may only succeed if you desire succeeding; you may only fail if you do not mind failing. ~Philippos",
    "Courage is resistance to fear, mastery of fear - not absense of fear. ~Mark Twain",
    "Only put off until tomorrow what you are willing to die having left undone. ~Pablo Picasso",
    "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily. ~Zig Ziglar",
    "We become what we think about most of the time, and that's the strangest secret. ~Earl Nightingale",
    "The only place where success comes before work is in the dictionary. ~Vidal Sassoon",
    "The best reason to start an organization is to make meaning; to create a product or service to make the world a better place. ~Guy Kawasaki",
    "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. ~Martha Stewart",
    "It's not what you look at that matters, it's what you see. ~Anonymous",
    "The road to success and the road to failure are almost exactly the same. ~Colin R. Davis",
    "The function of leadership is to produce more leaders, not more followers. ~Ralph Nader",
    "Success is liking yourself, liking what you do, and liking how you do it. ~Maya Angelou",
    "As we look ahead into the next century, leaders will be those who empower others. ~Bill Gates",
    "A real entrepreneur is somebody who has no safety net underneath them. ~Henry Kravis",
    "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. ~Mark Caine",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. ~Tony Robbins",
    "When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. ~Audre Lorde",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect. ~Mark Twain",
    "The successful warrior is the average man, with laser-like focus. ~Bruce Lee",
    "Take up one idea. Make that one idea your life -- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. ~Dale Carnegie",
    "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. ~ Jim Rohn",
    "If you genuinely want something, don't wait for it -- teach yourself to be impatient. ~Gurbaksh Chahal",
    "Don't let the fear of losing be greater than the excitement of winning. ~Robert Kiyosaki",
    "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! ~T. Harv Eker",
    "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. ~Steve Jobs",
    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier, wish you were better. ~Jim Rohn",
    "The number one reason people fail in life is because they listen to their friends, family, and neighbors. ~Napoleon Hill",
    "The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them. ~Denis Watiley",
    "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. ~Jane Smiley",
    "Success does not consist in never making mistakes but in never making the same one a second time. ~George Bernard Shaw",
    "I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. ~Diane Ackerman",
    "You must expect great things of yourself before you can do them. ~Michael Jordan",
    "Motivation is what gets you started. Habit is what keeps you going. ~Jim Ryun",
    "People rarely succeed unless they have fun in what they are doing. ~Dale Carnegie",
    "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. ~Ella Wheeler Wilcox",
    "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter. ~Francis Chan",
    "You've got to get up every morning with determination if you're going to go to bed with satisfaction. ~George Lorimer",
    "To be successful you must accept all challenges that come your way. You can't just accept the ones you like. ~Mike Gafka",
    "Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. ~ John C. Maxwell",
    "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. ~Wayne Dyer",
    "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.~ Anatole France",
    "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all. ~Dale Carnegie",
    "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. ~Booker T. Washington",
    "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. ~Theodore N. Vail",
    "It is better to fail in originality than to succeed in imitation. ~Herman Melville",
    "Fortune sides with him who dares. ~Virgil",
    "Little minds are tamed and subdued by misfortune; but great minds rise above it. ~Washington Irving",
    "Failure is the condiment that gives success its flavor. ~Truman Capote",
    "Don't let what you cannot do interfere with what you can do. ~John R. Wooden",
    "You may have to fight a battle more than once to win it. ~Margaret Thatcher",
    "Zero is the only real number that is neither positive nor negative.",
    "A circle has the largest area for a given perimeter of any 2D shape.",
    "The Fibonacci sequence appears in nature, such as in pinecones and sunflowers.",
    "Prime numbers are divisible only by 1 and themselves.",
    "The number π (pi) is irrational and never ends or repeats.",
    "A triangle’s interior angles always add up to 180°.",
    "The harmonic series 1 + 1/2 + 1/3 + 1/4 + ... diverges to infinity.",
    "There are infinitely many prime numbers — proven by Euclid.",
    "A square is both a rectangle and a rhombus.",
    "An irrational number cannot be written as a simple fraction.",
    "The derivative measures the rate of change of a function.",
    "The integral calculates the area under a curve.",
    "Euler’s formula relates five constants: e^{iπ} + 1 = 0.",
    "Negative numbers were once considered impossible in many ancient cultures.",
    "A googol is 10¹⁰⁰ — extremely large.",
    "The Mandelbrot set is created using a simple repeated equation.",
    "Imaginary numbers involve the square root of –1.",
    "Modular arithmetic is used in cryptography.",
    "A regular polygon has equal sides and equal angles.",
    "The probability of two people sharing a birthday in a group of 23 is over 50%.",
    "Pythagorean triples represent right triangles with integer sides.",
    "A factorial grows extremely fast: 10! = 3,628,800.",
    "Infinity is not a number but a concept of unboundedness.",
    "Fractals show self-similar patterns at all scales.",
    "The golden ratio is approximately 1.618.",
    "The area of a triangle = 1/2 × base × height.",
    "Complex numbers have a real and imaginary part.",
    "The number e ≈ 2.718 is the base of natural logarithms.",
    "Probability was developed to solve gambling problems.",
    "Cryptography often uses extremely large prime numbers.",
    "Symmetry is a key idea in geometry and physics.",
    "A matrix is a rectangular arrangement of numbers used in transformations.",
    "The sum of the first n natural numbers is n(n+1)/2.",
    "Water expands when it freezes — unusual for liquids.",
    "Light travels at 299,792,458 m/s in a vacuum.",
    "DNA carries genetic information in living organisms.",
    "The Earth rotates once every 24 hours.",
    "The Sun is a medium-sized star called a yellow dwarf.",
    "Photosynthesis converts sunlight into chemical energy.",
    "An atom consists of electrons, protons, and neutrons.",
    "Gravity is a force that attracts masses together.",
    "Sound travels faster in water than in air.",
    "A photon is a particle of light with no mass.",
    "The human body is about 60% water.",
    "The ozone layer absorbs harmful UV radiation.",
    "Viruses are not considered living organisms by traditional definitions.",
    "The moon causes ocean tides via gravitational pull.",
    "Black holes have gravity so strong that light cannot escape.",
    "Earth’s core is mostly iron and nickel.",
    "Carbon is the foundation of organic chemistry.",
    "Neutron stars are so dense that a teaspoon of material weighs billions of tons.",
    "Evolution explains the diversity of life on Earth.",
    "The Milky Way contains over 100 billion stars.",
    "Solar energy comes from nuclear fusion in the Sun.",
    "Absolute zero (–273.15°C) is the lowest possible temperature.",
    "Atoms are 99.9999999% empty space.",
    "Lightning heats the air to about 30,000°C — hotter than the Sun’s surface.",
    "Photosynthesis produces most of Earth’s oxygen.",
    "Water is the only substance found naturally on Earth in all three states: solid, liquid, gas.",
    "Plants absorb CO₂ and release O₂.",
    "Earth’s magnetic field protects us from solar wind.",
    "Life is believed to have begun around 3.5 billion years ago.",
    "The periodic table organizes elements by atomic number.",
    "A supernova is the explosive death of a massive star.",
    "The human brain has around 86 billion neurons.",
    "Bacteria are essential for digestion and nutrient recycling.",
    "The first programmable computer was created by Charles Babbage.",
    "Binary (0 and 1) is the fundamental language of computers.",
    "A transistor is the basic building block of modern electronics.",
    "Artificial intelligence uses algorithms to learn patterns.",
    "A CPU executes instructions and performs calculations.",
    "Moore’s law predicted transistor counts doubling every ~2 years.",
    "Wi-Fi uses radio waves to transmit data wirelessly.",
    "Bluetooth was named after a Viking king.",
    "Smartphones contain multiple sensors: gyroscope, accelerometer, GPS, etc.",
    "The internet is a global network of interconnected computers.",
    "A pixel is the smallest unit of a digital image.",
    "Cloud computing stores data on remote servers.",
    "HTML is the language for creating web pages.",
    "Encryption protects data by converting it into unreadable form.",
    "A GPU accelerates graphics and machine learning computations.",
    "The first 1GB hard drive (1980) weighed over 200 kg.",
    "USB stands for Universal Serial Bus.",
    "QR codes store data in black-and-white patterns.",
    "LEDs are efficient light sources using semiconductor materials.",
    "5G networks allow ultra-fast wireless communication.",
    "Neural networks mimic how human neurons process information.",
    "JavaScript powers interactive websites.",
    "Python is one of the most popular programming languages today.",
    "Robots automate tasks in manufacturing, medicine, and exploration.",
    "GPS relies on satellites orbiting Earth.",
    "The first website was published in 1991 by Tim Berners-Lee.",
    "SSDs are much faster than traditional hard drives.",
    "Blockchain stores data in linked, immutable records.",
    "Machine learning improves performance through experience.",
    "Drones use sensors for stability and navigation.",
    "Virtual reality creates immersive digital environments.",
    "Quantum computers use qubits instead of bits.",
    "Touchscreens detect input using electrical signals.",
    "Cybersecurity protects computer systems from unauthorized access.",
];